"""times table

Revision ID: 3751207ae6b4
Revises: 
Create Date: 2021-05-21 19:21:43.248504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3751207ae6b4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total', sa.String(length=80), nullable=True),
    sa.Column('minimum', sa.String(length=80), nullable=True),
    sa.Column('max', sa.String(length=80), nullable=True),
    sa.Column('average', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time')
    # ### end Alembic commands ###
